export const SOURCE_FORMAT_MAP = {
  // Core rulebooks
  PHB: "Player's Handbook (2014)",
  XPHB: "Player's Handbook (2024)",
  DMG: "Dungeon Master's Guide (2014)",
  XDMG: "Dungeon Master's Guide (2024)",
  MM: "Monster Manual (2014)",
  XMM: "Monster Manual (2024)",

  // Supplements
  XGE: "Xanathar's Guide to Everything (2017)",
  TCE: "Tasha's Cauldron of Everything (2020)",
  SCAG: "Sword Coast Adventurer's Guide (2015)",
  VGM: "Volo's Guide to Monsters (2016)",
  MTF: "Mordenkainen's Tome of Foes (2018)",
  MPMM: "Mordenkainen Presents: Monsters of the Multiverse (2022)",
  FTD: "Fizban's Treasury of Dragons (2021)",
  SCC: "Strixhaven: A Curriculum of Chaos (2021)",
  SAiS: "Spelljammer: Adventures in Space (2022)",
  BAM: "Boo's Astral Menagerie (2022)",
  MOT: "Mythic Odysseys of Theros (2020)",
  GGR: "Guildmasters' Guide to Ravnica (2018)",
  ERLW: "Eberron: Rising from the Last War (2019)",
  EGW: "Explorer's Guide to Wildemount (2020)",
  AI: "Acquisitions Incorporated (2019)",
  MaBJoV: "Minsc and Boo's Journal of Villainy (2022)",
  PSI: "Plane Shift: Innistrad (2016)",
  PSZ: "Plane Shift: Zendikar (2016)",
  PSA: "Plane Shift: Amonkhet (2017)",
  PSK: "Plane Shift: Kaladesh (2017)",
  PSX: "Plane Shift: Ixalan (2018)",
  PSD: "Plane Shift: Dominaria (2018)",
  FRAiF: "Forgotten Realms: Adventures in Faerûn (2025)",
  SADS: "Sapphire Anniversary Dice Set (2019)",
  BGG: "Bigby Presents: Glory of Giants (2023)",
  BMT: "The Book of Many Things (2024)",
  MCV4EC: "Monstrous Compendium Vol. 4: Eldraine Creatures (2023)",
  LR: "Locanth Rising (2019)",
  MCV1SC: "Monstrous Compendium Volume One (1989)",
  VRGR: "Van Richten's Guide to Ravenloft (2021)",
  ESK: "Essentials Kit (2019)",

  // Adventures
  LMoP: "Lost Mine of Phandelver (2014)",
  HotDQ: "Hoard of the Dragon Queen (2014)",
  RoT: "The Rise of Tiamat (2014)",
  PotA: "Princes of the Apocalypse (2015)",
  OotA: "Out of the Abyss (2015)",
  CoS: "Curse of Strahd (2016)",
  SKT: "Storm King's Thunder (2016)",
  TftYP: "Tales from the Yawning Portal (2017)",
  ToA: "Tomb of Annihilation (2017)",
  WDH: "Waterdeep: Dragon Heist (2018)",
  WDotMM: "Waterdeep: Dungeon of the Mad Mage (2018)",
  GoS: "Ghosts of Saltmarsh (2019)",
  BGDIA: "Baldur's Gate: Descent into Avernus (2019)",
  IDRotF: "Icewind Dale: Rime of the Frostmaiden (2020)",
  KftGV: "Keys from the Golden Vault (2023)",
  PaBTSO: "Phandelver and Below: The Shattered Obelisk (2023)",
  QftIS: "Quests from the Infinite Staircase (2024)",
  VEoR: "Vecna: Eve of Ruin (2024)",
  WDMM: "Waterdeep: Dungeon of the Mad Mage (2018)",
  IMR: "Infernal Machine Rebuild (2019)",
  LoX: "Light of Xaryxis (2022)",
  CoA: "Chains of Asmodeus (2023)",
  CRCotN: "Critical Role: Call of the Netherdeep (2022)",
  JttRC: "Journeys through the Radiant Citadel (2022)",
  WBtW: "The Wild Beyond the Witchlight (2021)",
  GotSF: "Giants of the Star Forge (2023)",
  DSotDQ: "Dragonlance: Shadow of the Dragon Queen (2022)",
  KKW: "Krenko's Way (2018)",
  OoW: "The Orrery Of The Wanderer (2024)",
  ToFW: "Turn of Fortune's Wheel (2023)",
  LLK: "Lost Laboratory of Kwalish (2018)",
  DC: "Divine Contention (2019)",
  SDW: "Sleeping Dragon's Wake (2019)",
  SLW: "Storm Lord's Wrath (2019)",
  DoSI: "Dragons of Stormwreck Isle (2022)",
};

export function formatSource(source = "") {
  if (!source) return "";
  return SOURCE_FORMAT_MAP[source] || source;
}
